version: 2
updates:

  - package-ecosystem: pip
    commit-message:
      prefix: "chore"
    directory: /support/modules-artifact-gen/tests
    schedule:
      interval: weekly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: gitsubmodule
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"

  - package-ecosystem: docker
    commit-message:
      prefix: "chore"
    directory: /tests
    schedule:
      interval: monthly
    reviewers:
      - "mendersoftware/client-dependabot-reviewers"
